name: Main Workflow

on:
  # push:
  #   branches: [ main ]
  pull_request:
    branches:
      - main
      - feature/*
jobs:
  call-reusable:
    name: 'reusable-flows'
    if: github.event_name == 'pull_request' 
    uses: ./.github/workflows/template.yml
    with:
      java-version: '17'
      maven-goals: 'clean install'
      working-directory: 'javatechbase'

