name: Main Workflow

on:
  pull_request:
    branches:
      - main
      - feature/*
jobs:
  call-reusable:
    name: 'reusable-flows'
    # if: github.event_name == 'pull_request' # eventtriggers if the pull request is open/updated
    uses: ./.github/workflows/template.yml
    with:
      java-version: '17'
      maven-goals: 'clean install'
      working-directory: 'javatechbase'

