name: Main Workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  call-reusable:
    uses: ./.github/workflows/template.yml
    with:
      java-version: '17'
      maven-goals: 'clean install'
      working-directory: 'javatechbase'
   # secrets:
   #   MAVEN_SECRET: ${{ secrets.MAVEN_SECRET }}

